package com.g_ara.gara;


import com.codename1.analytics.AnalyticsService;
import com.codename1.io.Log;
import com.codename1.io.NetworkManager;
import com.codename1.io.Preferences;
import com.codename1.notifications.LocalNotificationCallback;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import userclasses.StateMachine;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Gara implements LocalNotificationCallback {

    private Form current;

    public void init(Object context) {
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        Log.bindCrashProtection(true);
    }

    public void start() {
        if (Preferences.get("Analytics", false)) {
            AnalyticsService.setAppsMode(true);
            AnalyticsService.init("UA-80287405-1", "g-ara.com");
        }
        Display.getInstance().lockOrientation(true);
        NetworkManager.getInstance().updateThreadCount(2);

        if (current != null) {
            current.show();
            return;
        }
        new StateMachine("/theme");
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

    @Override
    public void localNotificationReceived(String notificationId) {
        Display.getInstance().callSerially(() -> {
            if (Preferences.get("sessionToken", "").length() > 0) {
                if (Display.getInstance().getCurrent() == null) {
                    Preferences.set("nId", notificationId);
                }
            }
        });
    }
}
