/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */


package userclasses;

import com.codename1.ui.Component;
import com.codename1.ui.Form;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.util.Resources;
import com.g_ara.gara.controller.Map;
import generated.StateMachineBase;

/**
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }

    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
    }


    @Override
    protected void postLogin(Form f) {

    }

    @Override
    protected void postHome(Form f) {

    }

    @Override
    protected void beforeHome(Form f) {
        new Map(fetchResourceFile()).initMap(f);
    }

    @Override
    protected void onCreateHome() {

    }

    @Override
    protected void onCars_CarsAction(Component c, ActionEvent event) {
        showForm("Car", null);
    }

    @Override
    protected void onChat_ChatAction(Component c, ActionEvent event) {

        showForm("Conversion", null);
    }

    @Override
    protected void onGroups_GroupsAction(Component c, ActionEvent event) {
        showForm("Group", null);

    
    }
}
